apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: oracle-db-scc
allowPrivilegedContainer: false
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:{{ .Release.Namespace }}:default
